name: MMOItems
version: ${project.version}
api-version: 1.19
main: net.Indyuce.mmoitems.MMOItems
author: Indyuce
description: ${project.description}
load-before: [ ]
load-after:
  - name: MythicLib
    bootstrap: false
dependencies:
  - name: MythicLib
    required: true
    bootstrap: false
  - name: MMOCore
    required: false
    bootstrap: false
  - name: MMOInventory
    required: false
    bootstrap: false
  - name: MythicMobs
    required: false
    bootstrap: false
  - name: PlaceholderAPI
    required: false
    bootstrap: false
  - name: Vault
    required: false
    bootstrap: false
  - name: WorldGuard
    required: false
    bootstrap: false
commands:
  mmoitems:
    description: MMOItems main command.
    aliases: [ mi ]
  updateitem:
    description: Update the item you are holding.
    aliases: [ upitem, itemup ]
    permission: mmoitems.update
permissions:
  mmoitems.admin:
    description: Access to admin commands.
    default: op
  mmoitems.update:
    description: Access to /updateitem.
    default: op
  mmoitems.edit.op:
    description: Ability to edit op stats like commands.
    default: false
  mmoitems.bypass.item:
    description: Bypasses item permission restriction.
    default: false
  mmoitems.bypass.ability:
    description: Bypasses ability permission restriction.
    default: false
  mmoitems.bypass.class:
    description: Bypasses item class restriction.
    default: false
  mmoitems.bypass.soulbound:
    description: Bypasses soulbound restriction.
    default: false
  mmoitems.bypass.level:
    description: Bypasses item level restriction.
    default: false
  mmoitems.update-notify:
    description: Receive a notification when a new update is available.
    default: op
  mmoitems.soulbound:
    description: Allows to use /soulbound.
    default: op